[package]
name = "vaultd"
version = "0.1.0"
edition = "2024"


[dependencies]
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
shared = { path = "../shared" }
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"